<?php require_once ('Menu.phtml');?>
    <div>
        <h1>Your tasks: </h1>
    </div>
<?php
$items = new TaskDataSet();
echo "<table border='1' class='table table-hover'>";//makes the table
echo "<th scope='col'>Task</th> <th scope='col'>Project</th> <th scope='col'>Tag</th> <th scope='col'>Start</th> <th scope='col'>End</th>";
@$row=$items->getFutureUserTasks($_SESSION["userID"]);

if(count($row) == 0)
{
    echo"</table>";
    echo"<h1>No tasks found. You can add tasks through the 'Add A Task' page.</h1>";
}
else {
    for ($i = 0; $i < count($row); $i++)//cycles through each record and outputs each field individually
    {
        if($i % 2 == 0)
        {
            echo"<tr class='table-active'>";
        }
        else echo"<tr class='table-active-1'>";

        echo"
                 <td>" . $row[$i]->getName() . "</td> 
                 <td>" . $row[$i]->getProject() . "</td> 
                 <td>" . $row[$i]->getCategory() . "</td> 
                 <td>" . $row[$i]->getStartDate() . "</td> 
                 <td>" . $row[$i]->getEndDate() . "</td> 
                 </tr>";
    }
    echo "</table>";
}
?>