<head>
    <link rel = "stylesheet" href = "theme.css"/>
</head>

<body>
    <form action = "login.php" method = "post" class = "submissionForm">
        <div class = "container">
            <label for = "username" class = "logInPage">Username</label>
            <input type = "text" placeholder = "Enter Username" name = "username" id = "username" required>

            <label for = "password" class = "logInPage">Password</label>
            <input type = "password" placeholder = "Enter Password" name = "password" id = "password" required>

            <button type = "submit" name = "loginButton" id = "loginButton">Login</button>
        </div>
    </form>
</body>